# Generated by Django 5.0.6 on 2024-06-19 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='available',
        ),
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_per_day',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Default Brand', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default='Default City', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='createdByEmail',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='car',
            name='fuelCapacity',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='car',
            name='image1',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='imageUrl1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='car',
            name='imageUrl2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='car',
            name='imageUrl3',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='car',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='car',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='car',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='car',
            name='ownerPhoneNumber',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='Default Model', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
