# Generated by Django 5.0.6 on 2024-06-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_available_remove_car_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image1',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image2',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image3',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
    ]
