# Generated by Django 5.0.6 on 2024-06-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_image1_alter_car_image2_alter_car_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image1',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image2',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image3',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
    ]
