# Generated by Django 5.0.6 on 2024-06-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_rentedcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedcar',
            name='rent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentedcar',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
